### PR TITLE
ensure that deploy user is used for all app-related setup

### PR DESCRIPTION
**Pull request by afeld**
Puts that intention in one place. Please confirm that using the `deployer` user for all those roles _was_ the intention 😃

### CODE REVIEW

**Comment by voodoorai2000** [comment]
Indeed 😌

**Comment by afeld** [comment]
Good to merge?

**Comment by voodoorai2000** [comment]
Hey @afeld,

I've run the installer in a fresh server with this code, but I'm getting this error:

```
TASK [galaxy/geerlingguy.nginx : Ensure nginx is installed.] *****************************************************************
[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present' instead.. This feature will be removed in 
version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [206.189.24.183]: FAILED! => {"cache_update_time": 1548762880, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx'' failed: E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "rc": 100, "stderr": "E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)", "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/raimondgarcia/Documents/workspace/ahora_madrid/ansible/installer/consul.retry
```

Looks like something is locked by the root user 🤔 
Would you mind having a look? 😌🙏

**Comment by afeld** [comment]
I believe that issue is unrelated - submitted #83 for it.

**Comment by voodoorai2000** [comment]
[The branch with the fix](https://github.com/consul/installer/pull/83) runs fine :relieved:
However, when adding also the two commits from this PR, I get the following error:
Looks like a permissions issue 🤔

```
TASK [nginx : Change default template] 
****************************************************************************************
fatal: [206.189.24.183]: FAILED! => {"changed": false, "checksum": "003c2bbb9fc1aa0df715463b04e4cb04f11eb35e", "msg": "Destination /etc/nginx/sites-enabled not writable"}
```

**Comment by afeld** [comment]
That's fixed by #85.

**Comment by voodoorai2000** [comment]
Aaaah indeed 👌

**Comment by voodoorai2000** [comment]
Thank you @afeld! 😌🎉

**Pull request merged**
