### PR TITLE
Add SMTP configuration

### PR DESCRIPTION
**Pull request by voodoorai2000**
What
===
Setup default configuration to send emails via SMTP

Why
===
This is a common pitfall and it was raising a nasty 500 error if not configured properly

Using a demo SMTP server for first installations
Please update with your own SMTP server credentials before launching 😌

### CODE REVIEW

**Comment by allthesignals** [comment]
I think this is producing a syntax error for the unicorn task:
In the generated config/environment/production file:

```
  # Use a different logger for distributed setups.
    port:                 "25",
```

I think this syntax is incorrect ruby.

**Comment by voodoorai2000** [comment]
Yes...! I stumbled into this too! Is it solved in the master branch for you @allthesignals?

**Comment by allthesignals** [comment]
@voodoorai2000 yes! Thank you. I neglected to mention that I am deploying a _forked_ version of Consul, which meant an out-of-date `production.rb` file. Thank you again!

**Comment by voodoorai2000** [comment]
Great! Thank you @allthesignals 🙏🏻🎉

One thing I neglected to say too, Sendgrid does not like the SMTP token to be public, so it will not work right now. 

Hopefully with Rails 5 encrypted secrets we can use it 😌 In the meantime other SMTP credentials will be needed 🙏🏻

**Pull request merged**
