### PR TITLE
split the database setup from the rest of the application

### PR DESCRIPTION
**Pull request by afeld**
For users on cloud hosting, recommended that they use managed databases instead of running it on the same server. Based on conversation [in Slack](https://consul.slack.com/archives/CFCBKA4MC/p1547701625001900).

### CODE REVIEW

**Comment by voodoorai2000** [comment]
Great! 

However we have many types of users, from very advanced, to people that do not know about dev ops. 

So one one of our objectives has been to make the Installer's default options enough to get the app up and running for everyone. 

How about maintaining by default the DB in the same machine and documenting how to setup the database using an external service?

**Comment by afeld** [comment]
Ok, solved that problem by having a single overarching playbook that calls two sub-playbooks. Mind taking another look?

**Comment by voodoorai2000** [comment]
Hmmm I solved the conflicts, downloaded this branch locally and rebased with master, but I'm still getting the nginx error that is solved in master 🤔 

```
TASK [nginx : Change default template] ****************************************************************************************
fatal: [206.189.24.183]: FAILED! => {"changed": false, "checksum": "003c2bbb9fc1aa0df715463b04e4cb04f11eb35e", "msg": "Destination /etc/nginx/sites-enabled not writable"}
```

Would you mind rebasing this PR with master, just to make sure everything is fine and it's just a git synchronization issue? 😌

**Comment by afeld** [comment]
Rebased!

**Comment by voodoorai2000** [comment]
Thank you!
Works like a charm 👌

**Pull request merged**
