### PR TITLE
[WORK IN PROGRESS] set up continuous integration

### PR DESCRIPTION
**Pull request by afeld**
You can see the builds [here](https://travis-ci.com/afeld/installer) until TravisCI is enabled on this repository. Builds on #71, #76, #78, #80.

### CODE REVIEW

**Comment by afeld** [comment]
This is going to take more work...let me know if you're interested in having continuous integration set up for the installer, and whether you'd prefer it be done in Travis or elsewhere.

**Comment by voodoorai2000** [comment]
CI 😍
Yes please @afeld, this would be magnificent!
+1 to Travis 👌

**Comment by afeld** [comment]
Current status: Travis seems to be doing something weird with RVM that I can't replicate elsewhere. Waiting on [debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/) to be enabled to figure out what's going on.

**Comment by voodoorai2000** [comment]
Thank you @afeld!

Closed in favor of https://github.com/consul/installer/pull/97

**Pull request closed without merging**
